// import { Chakra_Petch } from "next/font/google";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Provider from "../components/Provider";

// const chakra = Chakra_Petch({ 
//   weight: ["300", "400","500","600","700"],
//   subsets: ["latin"]
// });

const orbitron = Orbitron({ 
  weight: ["400", "500","600","700","800","900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log('Chakra class name:', orbitron.className);
  return (
    <html lang="en">
      <body className={`${orbitron.className} bg-image`}>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
